<a href="https://colab.research.google.com/github/2303A51572/DATA-SCIENCE/blob/main/lab_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# -----------------------------
# Step 1: Create Products dataset
# -----------------------------
products = pd.DataFrame({
    "product_id": [101, 102, 103, 104, 105],
    "product_name": ["Laptop", "Phone", "Tablet", "Headphones", "Charger"],
    "category": ["Electronics", "Electronics", "Electronics", "Accessories", "Accessories"],
    "price": [70000, 30000, 20000, 5000, 1000]
})

print("Products Dataset:")
print(products, "\n")

# -----------------------------
# Step 2: Create Sales dataset
# -----------------------------
sales = pd.DataFrame({
    "sale_id": [1, 2, 3, 4, 5, 6, 7],
    "product_id": [101, 102, 103, 104, 101, 105, 106],  # note: 106 has no matching product
    "quantity": [2, 5, 3, 10, 1, 15, 4]
})

print("Sales Dataset:")
print(sales, "\n")

# -----------------------------
# Step 3: Merge datasets
# -----------------------------
# Inner Join
inner_merged = pd.merge(sales, products, on="product_id", how="inner")
print("Merged Dataset (Inner Join):")
print(inner_merged, "\n")

# Outer Join
outer_merged = pd.merge(sales, products, on="product_id", how="outer")
print("Merged Dataset (Outer Join):")
print(outer_merged, "\n")

# -----------------------------
# Step 4: Compute Statistics
# -----------------------------
# Add revenue column
inner_merged["revenue"] = inner_merged["quantity"] * inner_merged["price"]

# Total revenue
total_revenue = inner_merged["revenue"].sum()

# Average product price
avg_price = products["price"].mean()

# Product-wise sales
product_sales = inner_merged.groupby("product_name")[["quantity", "revenue"]].sum().sort_values("revenue", ascending=False)

# Category-wise aggregation
category_sales = inner_merged.groupby("category")[["quantity", "revenue"]].sum().sort_values("revenue", ascending=False)

best_category = category_sales.index[0]

print("Total Revenue:", total_revenue)
print("Average Product Price:", avg_price, "\n")

print("Product-wise Sales & Revenue:")
print(product_sales, "\n")

print("Category-wise Sales & Revenue:")
print(category_sales, "\n")

print("Best-Selling Category:", best_category)

Products Dataset:
   product_id product_name     category  price
0         101       Laptop  Electronics  70000
1         102        Phone  Electronics  30000
2         103       Tablet  Electronics  20000
3         104   Headphones  Accessories   5000
4         105      Charger  Accessories   1000

Sales Dataset:
   sale_id  product_id  quantity
0        1         101         2
1        2         102         5
2        3         103         3
3        4         104        10
4        5         101         1
5        6         105        15
6        7         106         4

Merged Dataset (Inner Join):
   sale_id  product_id  quantity product_name     category  price
0        1         101         2       Laptop  Electronics  70000
1        2         102         5        Phone  Electronics  30000
2        3         103         3       Tablet  Electronics  20000
3        4         104        10   Headphones  Accessories   5000
4        5         101         1       Laptop  Electronics  70000
5        6         105        15      Charger  Accessories   1000

Merged Dataset (Outer Join):
   sale_id  product_id  quantity product_name     category    price
0        1         101         2       Laptop  Electronics  70000.0
1        5         101         1       Laptop  Electronics  70000.0
2        2         102         5        Phone  Electronics  30000.0
3        3         103         3       Tablet  Electronics  20000.0
4        4         104        10   Headphones  Accessories   5000.0
5        6         105        15      Charger  Accessories   1000.0
6        7         106         4          NaN          NaN      NaN

Total Revenue: 485000
Average Product Price: 25200.0

Product-wise Sales & Revenue:
              quantity  revenue
product_name
Laptop               3   210000
Phone                5   150000
Tablet               3    60000
Headphones          10    50000
Charger             15    15000

Category-wise Sales & Revenue:
             quantity  revenue
category
Electronics        11   420000
Accessories        25    65000

Best-Selling Category: Electronics

In [2]:
import pandas as pd

# --------------------------
# 1. Create Teachers Dataset
# --------------------------
teachers = pd.DataFrame({
    'teacher_id': [1, 2, 3, 4, 5],
    'teacher_name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'department': ['Math', 'Physics', 'Math', 'CS', 'CS']
})

print("Teachers Dataset:")
print(teachers, "\n")

# ------------------------
# 2. Create Courses Dataset
# ------------------------
courses = pd.DataFrame({
    'course_id': [101, 102, 103, 104, 105, 106, 107],
    'course_name': ['Algebra', 'Mechanics', 'Statistics', 'AI', 'ML', 'Quantum', 'Databases'],
    'teacher_id': [1, 2, 1, 4, 4, 2, 5]  # Note: Charlie (id=3) has no course
})

print("Courses Dataset:")
print(courses, "\n")

# ------------------------
# 3. Merge on teacher_id
# ------------------------
# Inner Join: only teachers with assigned courses
inner_merged = pd.merge(courses, teachers, on='teacher_id', how='inner')

# Left Join: all teachers included, courses if available
left_merged = pd.merge(teachers, courses, on='teacher_id', how='left')

print("Inner Join Result (only matched):")
print(inner_merged, "\n")

print("Left Join Result (all teachers included):")
print(left_merged, "\n")

# -------------------------------
# 4. Compute average courses/teacher
# -------------------------------
course_count = courses.groupby('teacher_id').size().reset_index(name='course_count')
teacher_courses = pd.merge(teachers, course_count, on='teacher_id', how='left').fillna(0)
avg_courses = teacher_courses['course_count'].mean()

print("Courses per Teacher:")
print(teacher_courses, "\n")
print(f"Average courses per teacher: {avg_courses:.2f}\n")

# -----------------------------------------
# 5. Group by department - total workload
# -----------------------------------------
dept_workload = teacher_courses.groupby('department')['course_count'].sum().reset_index()

print("Department-wise Workload Distribution:")
print(dept_workload, "\n")

# ------------------------
# 6. Discussion
# ------------------------
print("Discussion:")
print("1. Inner join shows only teachers who are assigned at least one course.")
print("2. Left join ensures all teachers are included, even if they have no courses.")
print("3. Average workload (courses per teacher) helps identify under/over-utilization.")
print("4. Department-wise workload distribution shows which departments carry more teaching responsibilities.")

Teachers Dataset:
   teacher_id teacher_name department
0           1        Alice       Math
1           2          Bob    Physics
2           3      Charlie       Math
3           4        David         CS
4           5          Eve         CS

Courses Dataset:
   course_id course_name  teacher_id
0        101     Algebra           1
1        102   Mechanics           2
2        103  Statistics           1
3        104          AI           4
4        105          ML           4
5        106     Quantum           2
6        107   Databases           5

Inner Join Result (only matched):
   course_id course_name  teacher_id teacher_name department
0        101     Algebra           1        Alice       Math
1        102   Mechanics           2          Bob    Physics
2        103  Statistics           1        Alice       Math
3        104          AI           4        David         CS
4        105          ML           4        David         CS
5        106     Quantum           2          Bob    Physics
6        107   Databases           5          Eve         CS

Left Join Result (all teachers included):
   teacher_id teacher_name department  course_id course_name
0           1        Alice       Math      101.0     Algebra
1           1        Alice       Math      103.0  Statistics
2           2          Bob    Physics      102.0   Mechanics
3           2          Bob    Physics      106.0     Quantum
4           3      Charlie       Math        NaN         NaN
5           4        David         CS      104.0          AI
6           4        David         CS      105.0          ML
7           5          Eve         CS      107.0   Databases

Courses per Teacher:
   teacher_id teacher_name department  course_count
0           1        Alice       Math           2.0
1           2          Bob    Physics           2.0
2           3      Charlie       Math           0.0
3           4        David         CS           2.0
4           5          Eve         CS           1.0

Average courses per teacher: 1.40

Department-wise Workload Distribution:
  department  course_count
0         CS           3.0
1       Math           2.0
2    Physics           2.0

Discussion:
1. Inner join shows only teachers who are assigned at least one course.
2. Left join ensures all teachers are included, even if they have no courses.
3. Average workload (courses per teacher) helps identify under/over-utilization.
4. Department-wise workload distribution shows which departments carry more teaching responsibilities.